run-tests:
	PYTHONPATH=. pytest -v

run-random:
	python3 run_lab.py --search random

run-bfs:
	python3 run_lab.py --search bfs

run-dfs:
	python3 run_lab.py --search dfs

run-astar:
	python3 run_lab.py --search astar